name: Deploy to GitHub Pages

on:
  push:
    branches: [main]  # Trigger on pushes to `main`

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu (faster/more reliable than macOS)

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x  # Next.js requires Node.js 16+
          cache: 'npm'

      # 3. Install dependencies, build, and export
      - run: npx browserslist@latest --update-db  # Fix browserslist warning
      - run: npm ci
      - run: npm run build
      - run: npm run export
      - run: touch ./out/.nojekyll  # Disable Jekyll processing

      # 4. Deploy to GitHub Pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master  # GitHub Pages branch
          folder: out    # Deploy the `out/` folder
          clean: true    # Delete old files
          token: ${{ secrets.GITHUB_TOKEN }}  # Critical for permissions!
